# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under SGITHUB WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: PerfAction for JMeter
        # You may pin to the exact commit or the version.
        # uses: QAInsights/PerfAction@2c22274f313e13ce9ddaf60c9f337a0e628fcb9d
        uses: QAInsights/PerfAction@v5.6.3
        with:
          # jmeter tst plan to execute
          test-plan-path: './HTTP(S) Test Script Recorder.jmx'
          result-file: './results/Test_Output.jtl'

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results/Test_Output.jtl
          if-no-files-found: error
